/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmPrincipal.java
 *
 * Created on 23-oct-2011, 16:17:10
 */
package stinventario;

import clases.clsCaja;
import clases.clsComboBox;
import clases.clsFacturero;
import clases.clsPermisos;
import producto.frmProductosAdd;
import clases.clsUtils;
import proveedores.frmProveedorAdd;
import proveedores.frmProveedorDel;
import proveedores.frmProveedorMenu;
import proveedores.frmProveedorMod;
import clientes.frmClienteMod;
import clientes.frmClienteDel;
import clientes.frmClienteAdd;
import clientes.frmReporteSector;
import index.main;
import java.awt.Dimension;
import org.jdesktop.application.Action;
import clases.clsReporte;
import javax.swing.ImageIcon;
import pos.frmMenu;
import javax.swing.JOptionPane;
import pago.frmPagoHistoricoAdd;
import pos.frmFactHisto;
import producto.frmKardex;
import producto.frmProductosDel;
import producto.frmProductosMod;
import usuarios.frmClaveCambiar;
import usuarios.frmUsuarioPermisos;
import com.jidesoft.swing.MarqueePane;
import index.frmAcerca;
import index.frmAuditoria;
import index.frmRespaldarDB;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.Timer;
import nomina.frmEmpleadoAdd;
import pago.frmPagoAdd;
import pos.frmAbrirCaja;
import pos.frmCerrarCaja;
import pos.frmEgresoDinero;
import pos.frmFacturaSeek;
import pos.frmFacturar;
import pos.frmFacturero;
import producto.frmCompras;
import producto.frmGrupoAdd;
import usuarios.frmNuevoUsuario;

/**
 *
 * @author Kaiser
 */
public class frmPrincipal extends javax.swing.JFrame {
    clsReporte objReporte = new clsReporte();
    clsUtils objUtils = new clsUtils();
    clsPermisos objPermisos = new clsPermisos();
    clsCaja objCaja = new clsCaja();
    clsFacturero objFacturero = new clsFacturero();
    
    boolean permitido;
    /** Creates new form frmPrincipal */
    public frmPrincipal() {
        initComponents();
        
        this.setTitle(objUtils.nombreLargoSistema);        
        lblUsuario.setText(main.nameUser);        
        jXTaskPane1.setTitle("Clientes");
        jXTaskPane2.setTitle("Proveedores");
        jXTaskPane3.setTitle("Productos");
        this.setIconImage(new ImageIcon(getClass().getResource("resources/iconoMain.png")).getImage()); 
        lblPendiente.setText("");
        boolean exito = objCaja.consultarCajaAbierta(index.main.idUser);
        if(exito)
        {
            lblPendiente.setText("TIENE PENDIENTE CERRAR CAJA");
            btnAbrir.setEnabled(false);  
            btnFacturar.setEnabled(true);
            btnPagos.setEnabled(true);
            btnCerrar.setEnabled(true); 
            btnEgreso.setEnabled(true); 
        }   
        
        
        Timer timer = new Timer (1000, new ActionListener ()
        {
            public void actionPerformed(ActionEvent e)
            {
                boolean exito = objCaja.consultarCajaAbierta(index.main.idUser);
                if(exito)
                {
                    lblPendiente.setText("TIENE PENDIENTE CERRAR CAJA");
                    btnAbrir.setEnabled(false);  
                    btnFacturar.setEnabled(true);
                    btnPagos.setEnabled(true);
                    btnCerrar.setEnabled(true); 
                    btnEgreso.setEnabled(true); 
                }   
                else
                {
                    lblPendiente.setText("");
                    btnAbrir.setEnabled(true);  
                    btnFacturar.setEnabled(false);
                    btnPagos.setEnabled(false);
                    btnCerrar.setEnabled(false); 
                    btnEgreso.setEnabled(false); 
                }
             }
        });


        timer.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnAbrir = new javax.swing.JButton();
        btnFacturar = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnEgreso = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblLogo = new javax.swing.JLabel();
        jXTaskPaneContainer2 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        jXHyperlink1 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink2 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink3 = new org.jdesktop.swingx.JXHyperlink();
        jXTaskPane2 = new org.jdesktop.swingx.JXTaskPane();
        jXHyperlink4 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink5 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink6 = new org.jdesktop.swingx.JXHyperlink();
        jXTaskPane3 = new org.jdesktop.swingx.JXTaskPane();
        jXHyperlink7 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink8 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink9 = new org.jdesktop.swingx.JXHyperlink();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblPendiente = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();

        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel2.setName("jPanel2"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stinventario.STInventarioApp.class).getContext().getResourceMap(frmPrincipal.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setLocationByPlatform(true);
        setName("Form"); // NOI18N

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        btnAbrir.setIcon(resourceMap.getIcon("btnAbrir.icon")); // NOI18N
        btnAbrir.setText(resourceMap.getString("btnAbrir.text")); // NOI18N
        btnAbrir.setFocusable(false);
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setName("btnAbrir"); // NOI18N
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAbrir);

        btnFacturar.setIcon(resourceMap.getIcon("btnFacturar.icon")); // NOI18N
        btnFacturar.setText(resourceMap.getString("btnFacturar.text")); // NOI18N
        btnFacturar.setEnabled(false);
        btnFacturar.setFocusable(false);
        btnFacturar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFacturar.setName("btnFacturar"); // NOI18N
        btnFacturar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFacturar);

        btnPagos.setIcon(resourceMap.getIcon("btnPagos.icon")); // NOI18N
        btnPagos.setText(resourceMap.getString("btnPagos.text")); // NOI18N
        btnPagos.setEnabled(false);
        btnPagos.setFocusable(false);
        btnPagos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPagos.setName("btnPagos"); // NOI18N
        btnPagos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPagos);

        btnCerrar.setIcon(resourceMap.getIcon("btnCerrar.icon")); // NOI18N
        btnCerrar.setText(resourceMap.getString("btnCerrar.text")); // NOI18N
        btnCerrar.setEnabled(false);
        btnCerrar.setFocusable(false);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setName("btnCerrar"); // NOI18N
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCerrar);

        btnEgreso.setIcon(resourceMap.getIcon("btnEgreso.icon")); // NOI18N
        btnEgreso.setText(resourceMap.getString("btnEgreso.text")); // NOI18N
        btnEgreso.setEnabled(false);
        btnEgreso.setFocusable(false);
        btnEgreso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEgreso.setName("btnEgreso"); // NOI18N
        btnEgreso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEgresoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEgreso);

        jSeparator6.setName("jSeparator6"); // NOI18N
        jToolBar1.add(jSeparator6);

        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton3.setIcon(resourceMap.getIcon("jButton3.icon")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setName("jButton3"); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jToolBar1.add(jSeparator1);

        jSeparator3.setName("jSeparator3"); // NOI18N
        jToolBar1.add(jSeparator3);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(stinventario.STInventarioApp.class).getContext().getActionMap(frmPrincipal.class, this);
        jButton2.setAction(actionMap.get("quit")); // NOI18N
        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jDesktopPane1.setBackground(resourceMap.getColor("jDesktopPane1.background")); // NOI18N
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDesktopPane1.setName("jDesktopPane1"); // NOI18N
        jDesktopPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jDesktopPane1ComponentResized(evt);
            }
        });

        filler1.setName("filler1"); // NOI18N
        filler1.setBounds(240, 110, 0, 0);
        jDesktopPane1.add(filler1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(resourceMap.getIcon("lblLogo.icon")); // NOI18N
        lblLogo.setText(resourceMap.getString("lblLogo.text")); // NOI18N
        lblLogo.setAlignmentX(javax.swing.SwingConstants.CENTER);
        lblLogo.setAlignmentY(javax.swing.SwingConstants.CENTER);
        lblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLogo.setName("lblLogo"); // NOI18N
        lblLogo.setBounds(10, -90, 640, 510);
        jDesktopPane1.add(lblLogo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jXTaskPaneContainer2.setName("jXTaskPaneContainer2"); // NOI18N

        jXTaskPane1.setName("jXTaskPane1"); // NOI18N

        jXHyperlink1.setIcon(resourceMap.getIcon("jXHyperlink1.icon")); // NOI18N
        jXHyperlink1.setText(resourceMap.getString("jXHyperlink1.text")); // NOI18N
        jXHyperlink1.setName("jXHyperlink1"); // NOI18N
        jXHyperlink1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink1ActionPerformed(evt);
            }
        });
        jXTaskPane1.getContentPane().add(jXHyperlink1);

        jXHyperlink2.setIcon(resourceMap.getIcon("jXHyperlink2.icon")); // NOI18N
        jXHyperlink2.setText(resourceMap.getString("jXHyperlink2.text")); // NOI18N
        jXHyperlink2.setName("jXHyperlink2"); // NOI18N
        jXHyperlink2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink2ActionPerformed(evt);
            }
        });
        jXTaskPane1.getContentPane().add(jXHyperlink2);

        jXHyperlink3.setIcon(resourceMap.getIcon("jXHyperlink3.icon")); // NOI18N
        jXHyperlink3.setText(resourceMap.getString("jXHyperlink3.text")); // NOI18N
        jXHyperlink3.setName("jXHyperlink3"); // NOI18N
        jXHyperlink3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink3ActionPerformed(evt);
            }
        });
        jXTaskPane1.getContentPane().add(jXHyperlink3);

        jXTaskPaneContainer2.add(jXTaskPane1);

        jXTaskPane2.setName("jXTaskPane2"); // NOI18N

        jXHyperlink4.setIcon(resourceMap.getIcon("jXHyperlink4.icon")); // NOI18N
        jXHyperlink4.setText(resourceMap.getString("jXHyperlink4.text")); // NOI18N
        jXHyperlink4.setName("jXHyperlink4"); // NOI18N
        jXHyperlink4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink4ActionPerformed(evt);
            }
        });
        jXTaskPane2.getContentPane().add(jXHyperlink4);

        jXHyperlink5.setIcon(resourceMap.getIcon("jXHyperlink5.icon")); // NOI18N
        jXHyperlink5.setText(resourceMap.getString("jXHyperlink5.text")); // NOI18N
        jXHyperlink5.setName("jXHyperlink5"); // NOI18N
        jXHyperlink5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink5ActionPerformed(evt);
            }
        });
        jXTaskPane2.getContentPane().add(jXHyperlink5);

        jXHyperlink6.setIcon(resourceMap.getIcon("jXHyperlink6.icon")); // NOI18N
        jXHyperlink6.setText(resourceMap.getString("jXHyperlink6.text")); // NOI18N
        jXHyperlink6.setName("jXHyperlink6"); // NOI18N
        jXHyperlink6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink6ActionPerformed(evt);
            }
        });
        jXTaskPane2.getContentPane().add(jXHyperlink6);

        jXTaskPaneContainer2.add(jXTaskPane2);

        jXTaskPane3.setName("jXTaskPane3"); // NOI18N

        jXHyperlink7.setIcon(resourceMap.getIcon("jXHyperlink7.icon")); // NOI18N
        jXHyperlink7.setText(resourceMap.getString("jXHyperlink7.text")); // NOI18N
        jXHyperlink7.setName("jXHyperlink7"); // NOI18N
        jXHyperlink7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink7ActionPerformed(evt);
            }
        });
        jXTaskPane3.getContentPane().add(jXHyperlink7);

        jXHyperlink8.setIcon(resourceMap.getIcon("jXHyperlink8.icon")); // NOI18N
        jXHyperlink8.setText(resourceMap.getString("jXHyperlink8.text")); // NOI18N
        jXHyperlink8.setName("jXHyperlink8"); // NOI18N
        jXHyperlink8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink8ActionPerformed(evt);
            }
        });
        jXTaskPane3.getContentPane().add(jXHyperlink8);

        jXHyperlink9.setIcon(resourceMap.getIcon("jXHyperlink9.icon")); // NOI18N
        jXHyperlink9.setText(resourceMap.getString("jXHyperlink9.text")); // NOI18N
        jXHyperlink9.setName("jXHyperlink9"); // NOI18N
        jXHyperlink9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink9ActionPerformed(evt);
            }
        });
        jXTaskPane3.getContentPane().add(jXHyperlink9);

        jXTaskPaneContainer2.add(jXTaskPane3);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setName("jPanel3"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        lblUsuario.setText(resourceMap.getString("lblUsuario.text")); // NOI18N
        lblUsuario.setName("lblUsuario"); // NOI18N

        lblPendiente.setFont(resourceMap.getFont("lblPendiente.font")); // NOI18N
        lblPendiente.setForeground(resourceMap.getColor("lblPendiente.foreground")); // NOI18N
        lblPendiente.setIcon(resourceMap.getIcon("lblPendiente.icon")); // NOI18N
        lblPendiente.setText(resourceMap.getString("lblPendiente.text")); // NOI18N
        lblPendiente.setName("lblPendiente"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsuario)
                .addGap(30, 30, 30)
                .addComponent(lblPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUsuario)
                    .addComponent(lblPendiente))
                .addContainerGap())
        );

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N

        jMenu15.setText(resourceMap.getString("jMenu15.text")); // NOI18N
        jMenu15.setName("jMenu15"); // NOI18N

        jMenuItem32.setText(resourceMap.getString("jMenuItem32.text")); // NOI18N
        jMenuItem32.setName("jMenuItem32"); // NOI18N
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem32);

        jMenu1.add(jMenu15);

        jMenuItem1.setIcon(resourceMap.getIcon("jMenuItem1.icon")); // NOI18N
        jMenuItem1.setText(resourceMap.getString("jMenuItem1.text")); // NOI18N
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu5.setText(resourceMap.getString("jMenu5.text")); // NOI18N
        jMenu5.setName("jMenu5"); // NOI18N

        jMenuItem6.setIcon(resourceMap.getIcon("jMenuItem6.icon")); // NOI18N
        jMenuItem6.setText(resourceMap.getString("jMenuItem6.text")); // NOI18N
        jMenuItem6.setName("jMenuItem6"); // NOI18N
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem7.setIcon(resourceMap.getIcon("jMenuItem7.icon")); // NOI18N
        jMenuItem7.setText(resourceMap.getString("jMenuItem7.text")); // NOI18N
        jMenuItem7.setName("jMenuItem7"); // NOI18N
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem11.setIcon(resourceMap.getIcon("jMenuItem11.icon")); // NOI18N
        jMenuItem11.setText(resourceMap.getString("jMenuItem11.text")); // NOI18N
        jMenuItem11.setName("jMenuItem11"); // NOI18N
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jSeparator2.setName("jSeparator2"); // NOI18N
        jMenu5.add(jSeparator2);

        jMenu6.setIcon(resourceMap.getIcon("jMenu6.icon")); // NOI18N
        jMenu6.setText(resourceMap.getString("jMenu6.text")); // NOI18N
        jMenu6.setName("jMenu6"); // NOI18N

        jMenuItem10.setIcon(resourceMap.getIcon("jMenuItem10.icon")); // NOI18N
        jMenuItem10.setText(resourceMap.getString("jMenuItem10.text")); // NOI18N
        jMenuItem10.setName("jMenuItem10"); // NOI18N
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuItem28.setIcon(resourceMap.getIcon("jMenuItem28.icon")); // NOI18N
        jMenuItem28.setText(resourceMap.getString("jMenuItem28.text")); // NOI18N
        jMenuItem28.setName("jMenuItem28"); // NOI18N
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem28);

        jMenuItem13.setIcon(resourceMap.getIcon("jMenuItem13.icon")); // NOI18N
        jMenuItem13.setText(resourceMap.getString("jMenuItem13.text")); // NOI18N
        jMenuItem13.setEnabled(false);
        jMenuItem13.setName("jMenuItem13"); // NOI18N
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem13);

        jMenu5.add(jMenu6);

        jMenuBar1.add(jMenu5);

        jMenu2.setText(resourceMap.getString("jMenu2.text")); // NOI18N
        jMenu2.setName("jMenu2"); // NOI18N

        jMenuItem2.setIcon(resourceMap.getIcon("jMenuItem2.icon")); // NOI18N
        jMenuItem2.setText(resourceMap.getString("jMenuItem2.text")); // NOI18N
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem8.setIcon(resourceMap.getIcon("jMenuItem8.icon")); // NOI18N
        jMenuItem8.setText(resourceMap.getString("jMenuItem8.text")); // NOI18N
        jMenuItem8.setName("jMenuItem8"); // NOI18N
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem12.setIcon(resourceMap.getIcon("jMenuItem12.icon")); // NOI18N
        jMenuItem12.setText(resourceMap.getString("jMenuItem12.text")); // NOI18N
        jMenuItem12.setName("jMenuItem12"); // NOI18N
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuBar1.add(jMenu2);

        jMenu14.setText(resourceMap.getString("jMenu14.text")); // NOI18N
        jMenu14.setName("jMenu14"); // NOI18N

        jMenuItem31.setText(resourceMap.getString("jMenuItem31.text")); // NOI18N
        jMenuItem31.setName("jMenuItem31"); // NOI18N
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem31);

        jMenuBar1.add(jMenu14);

        jMenu3.setText(resourceMap.getString("jMenu3.text")); // NOI18N
        jMenu3.setName("jMenu3"); // NOI18N

        jMenuItem3.setIcon(resourceMap.getIcon("jMenuItem3.icon")); // NOI18N
        jMenuItem3.setText(resourceMap.getString("jMenuItem3.text")); // NOI18N
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem14.setIcon(resourceMap.getIcon("jMenuItem14.icon")); // NOI18N
        jMenuItem14.setText(resourceMap.getString("jMenuItem14.text")); // NOI18N
        jMenuItem14.setName("jMenuItem14"); // NOI18N
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuItem17.setIcon(resourceMap.getIcon("jMenuItem17.icon")); // NOI18N
        jMenuItem17.setText(resourceMap.getString("jMenuItem17.text")); // NOI18N
        jMenuItem17.setName("jMenuItem17"); // NOI18N
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem17);

        jSeparator4.setName("jSeparator4"); // NOI18N
        jMenu3.add(jSeparator4);

        jMenuItem18.setIcon(resourceMap.getIcon("jMenuItem18.icon")); // NOI18N
        jMenuItem18.setText(resourceMap.getString("jMenuItem18.text")); // NOI18N
        jMenuItem18.setName("jMenuItem18"); // NOI18N
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem18);

        jMenuBar1.add(jMenu3);

        jMenu13.setText(resourceMap.getString("jMenu13.text")); // NOI18N
        jMenu13.setName("jMenu13"); // NOI18N

        jMenuItem23.setIcon(resourceMap.getIcon("jMenuItem23.icon")); // NOI18N
        jMenuItem23.setText(resourceMap.getString("jMenuItem23.text")); // NOI18N
        jMenuItem23.setName("jMenuItem23"); // NOI18N
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem23);

        jMenuBar1.add(jMenu13);

        jMenu7.setText(resourceMap.getString("jMenu7.text")); // NOI18N
        jMenu7.setName("jMenu7"); // NOI18N

        jMenuItem15.setText(resourceMap.getString("jMenuItem15.text")); // NOI18N
        jMenuItem15.setName("jMenuItem15"); // NOI18N
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem15);

        jMenuItem16.setText(resourceMap.getString("jMenuItem16.text")); // NOI18N
        jMenuItem16.setName("jMenuItem16"); // NOI18N
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem16);

        jSeparator5.setName("jSeparator5"); // NOI18N
        jMenu7.add(jSeparator5);

        jMenuItem19.setIcon(resourceMap.getIcon("jMenuItem19.icon")); // NOI18N
        jMenuItem19.setText(resourceMap.getString("jMenuItem19.text")); // NOI18N
        jMenuItem19.setName("jMenuItem19"); // NOI18N
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem19);

        jMenuBar1.add(jMenu7);

        jMenu9.setText(resourceMap.getString("jMenu9.text")); // NOI18N
        jMenu9.setName("jMenu9"); // NOI18N

        jMenu8.setIcon(resourceMap.getIcon("jMenu8.icon")); // NOI18N
        jMenu8.setText(resourceMap.getString("jMenu8.text")); // NOI18N
        jMenu8.setName("jMenu8"); // NOI18N

        jMenuItem20.setText(resourceMap.getString("jMenuItem20.text")); // NOI18N
        jMenuItem20.setName("jMenuItem20"); // NOI18N
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem20);

        jMenuItem21.setText(resourceMap.getString("jMenuItem21.text")); // NOI18N
        jMenuItem21.setName("jMenuItem21"); // NOI18N
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem21);

        jMenu9.add(jMenu8);

        jMenuBar1.add(jMenu9);

        jMenu11.setText(resourceMap.getString("jMenu11.text")); // NOI18N
        jMenu11.setName("jMenu11"); // NOI18N

        jMenuItem25.setText(resourceMap.getString("jMenuItem25.text")); // NOI18N
        jMenuItem25.setName("jMenuItem25"); // NOI18N
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem25);

        jMenuItem24.setText(resourceMap.getString("jMenuItem24.text")); // NOI18N
        jMenuItem24.setName("jMenuItem24"); // NOI18N
        jMenu11.add(jMenuItem24);

        jMenuBar1.add(jMenu11);

        jMenu12.setText(resourceMap.getString("jMenu12.text")); // NOI18N
        jMenu12.setName("jMenu12"); // NOI18N

        jMenuItem27.setText(resourceMap.getString("jMenuItem27.text")); // NOI18N
        jMenuItem27.setName("jMenuItem27"); // NOI18N
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem27);

        jMenuItem30.setText(resourceMap.getString("jMenuItem30.text")); // NOI18N
        jMenuItem30.setName("jMenuItem30"); // NOI18N
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem30);

        jSeparator7.setName("jSeparator7"); // NOI18N
        jMenu12.add(jSeparator7);

        jMenuItem29.setIcon(resourceMap.getIcon("jMenuItem29.icon")); // NOI18N
        jMenuItem29.setText(resourceMap.getString("jMenuItem29.text")); // NOI18N
        jMenuItem29.setName("jMenuItem29"); // NOI18N
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem29);

        jMenuBar1.add(jMenu12);

        jMenu4.setText(resourceMap.getString("jMenu4.text")); // NOI18N
        jMenu4.setName("jMenu4"); // NOI18N

        jMenuItem4.setIcon(resourceMap.getIcon("jMenuItem4.icon")); // NOI18N
        jMenuItem4.setText(resourceMap.getString("jMenuItem4.text")); // NOI18N
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setIcon(resourceMap.getIcon("jMenuItem5.icon")); // NOI18N
        jMenuItem5.setText(resourceMap.getString("jMenuItem5.text")); // NOI18N
        jMenuItem5.setName("jMenuItem5"); // NOI18N
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem9.setIcon(resourceMap.getIcon("jMenuItem9.icon")); // NOI18N
        jMenuItem9.setText(resourceMap.getString("jMenuItem9.text")); // NOI18N
        jMenuItem9.setName("jMenuItem9"); // NOI18N
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem22.setText(resourceMap.getString("jMenuItem22.text")); // NOI18N
        jMenuItem22.setName("jMenuItem22"); // NOI18N
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem22);

        jMenuBar1.add(jMenu4);

        jMenu16.setText(resourceMap.getString("jMenu16.text")); // NOI18N
        jMenu16.setEnabled(false);
        jMenu16.setName("jMenu16"); // NOI18N

        jMenuItem33.setText(resourceMap.getString("jMenuItem33.text")); // NOI18N
        jMenuItem33.setName("jMenuItem33"); // NOI18N
        jMenu16.add(jMenuItem33);

        jMenuItem34.setText(resourceMap.getString("jMenuItem34.text")); // NOI18N
        jMenuItem34.setName("jMenuItem34"); // NOI18N
        jMenu16.add(jMenuItem34);

        jMenuItem35.setText(resourceMap.getString("jMenuItem35.text")); // NOI18N
        jMenuItem35.setName("jMenuItem35"); // NOI18N
        jMenu16.add(jMenuItem35);

        jMenuBar1.add(jMenu16);

        jMenu10.setText(resourceMap.getString("jMenu10.text")); // NOI18N
        jMenu10.setName("jMenu10"); // NOI18N

        jMenuItem26.setIcon(resourceMap.getIcon("jMenuItem26.icon")); // NOI18N
        jMenuItem26.setText(resourceMap.getString("jMenuItem26.text")); // NOI18N
        jMenuItem26.setName("jMenuItem26"); // NOI18N
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem26);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXTaskPaneContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jXTaskPaneContainer2, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    objReporte.ejecutarReporte("rptProveedores");
    
}//GEN-LAST:event_jMenuItem4ActionPerformed

    void mostrarIngresoCliente()
    {
        frmClienteAdd formulario = new frmClienteAdd();
        mostrarJInternalCentrado(formulario); 
    }


    void mostrarModificarCliente()
    {
        frmClienteMod formulario = new frmClienteMod();
        mostrarJInternalCentrado(formulario); 
    }

    void mostrarIngresoProveedores()
    {
        frmProveedorAdd formulario = new frmProveedorAdd();
        mostrarJInternalCentrado(formulario); 
    }  

    void mostrarIngresoProductos()
    {
        frmProductosAdd formulario = new frmProductosAdd();
        mostrarJInternalCentrado(formulario); 
    }

    void mostrarProductoMod()
    {
        permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmProductosMod");
        if(permitido)
        {   
            frmProductosMod formulario = new frmProductosMod();    
            mostrarJInternalCentrado(formulario); 
        }
        else
        {
            JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
        }    
    }
    
    void mostrarCompras()
    {
        frmCompras formulario = new frmCompras();
        mostrarJInternalCentrado(formulario); 
    }
    
    void mostrarProductoDel()
    {
        permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmProductosDel");
        if(permitido)
        {   
            frmProductosDel formulario = new frmProductosDel();    
            mostrarJInternalCentrado(formulario); 
        }
        else
        {
            JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
        }    
    }

    void mostrarEliminarCliente()
    {
        frmClienteDel formulario = new frmClienteDel();
        mostrarJInternalCentrado(formulario); 
    }

    void mostrarEliminarProveedor()
    {
        frmProveedorDel formulario = new frmProveedorDel();    
        mostrarJInternalCentrado(formulario); 
    }

    void mostrarAsignacionPermisos()
    {
        permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmUsuarioPermisos");
        if(permitido)
        {   
            frmUsuarioPermisos formulario = new frmUsuarioPermisos();
            mostrarJInternalCentrado(formulario);
        }
        else
        {
            JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
        }

    }
    
    void mostrarPagosHistorico()
    {
        permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmPagoHistoricoAdd");
        if(permitido)
        {  
            frmPagoHistoricoAdd formulario = new frmPagoHistoricoAdd();
            mostrarJInternalCentrado(formulario); 
        }
        else
        {
            JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
        }
    }
    
     void mostrarKardex()
    {
        permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmKardex");
        if(permitido)
        {  
            frmKardex formulario = new frmKardex();
            mostrarJInternalCentrado(formulario); 
        }
        else
        {
            JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
        }
    }
     
    void mostrarInicioCaja()
    {
        permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmFactHisto");
        if(permitido)
        {  
            frmMenu formulario = new frmMenu();
            mostrarJInternalCentrado(formulario); 
        }
        else
        {
            JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
        }   
    }
    
    void mostrarFacturarHistorico()
    {
        permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmFactHisto");
        if(permitido)
        {  
            /*frmFactHisto formulario = new frmFactHisto(this, true);
            formulario.setLocationRelativeTo(null);
            formulario.setVisible(true);*/
            frmFactHisto formulario = new frmFactHisto();
            mostrarJInternalCentrado(formulario); 
        }
        else
        {
            JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
        }    
    }
    
    void mostrarReportePorSector()
    {
        frmReporteSector formulario = new frmReporteSector();
        mostrarJInternalCentrado(formulario);    
    }
    
    void mostrarCambioClave()
    {
        frmClaveCambiar formulario = new frmClaveCambiar();
        mostrarJInternalCentrado(formulario);    
    }

    public static void mostrarJInternalCentrado(javax.swing.JInternalFrame formulario)
    {
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = formulario.getSize();
        formulario.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
        (desktopSize.height- jInternalFrameSize.height)/2);

        jDesktopPane1.add(formulario);
        formulario.show(); 
    }

private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
    objReporte.ejecutarReporte("rptProductos");
}//GEN-LAST:event_jMenuItem5ActionPerformed

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    mostrarIngresoProductos();
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    mostrarIngresoProveedores();
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void jXHyperlink1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink1ActionPerformed
     mostrarIngresoCliente();
}//GEN-LAST:event_jXHyperlink1ActionPerformed

    private void jDesktopPane1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDesktopPane1ComponentResized
        lblLogo.setLocation((jDesktopPane1.getWidth() - lblLogo.getWidth())/2, 
        (jDesktopPane1.getHeight() - lblLogo.getHeight())/2);
    }//GEN-LAST:event_jDesktopPane1ComponentResized

private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
    mostrarIngresoCliente();
}//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        mostrarModificarCliente();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jXHyperlink2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink2ActionPerformed
        mostrarModificarCliente();
    }//GEN-LAST:event_jXHyperlink2ActionPerformed

    private void jXHyperlink4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink4ActionPerformed
        mostrarIngresoProveedores();
    }//GEN-LAST:event_jXHyperlink4ActionPerformed

    private void jXHyperlink5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink5ActionPerformed
        mostrarModificarProveedores();
    }//GEN-LAST:event_jXHyperlink5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        mostrarModificarProveedores();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jXHyperlink7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink7ActionPerformed
        mostrarIngresoProductos();
    }//GEN-LAST:event_jXHyperlink7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        objReporte.ejecutarReporte("rptClientes");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        mostrarEliminarCliente();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jXHyperlink3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink3ActionPerformed
        mostrarEliminarCliente();
    }//GEN-LAST:event_jXHyperlink3ActionPerformed

    private void jXHyperlink6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink6ActionPerformed
        mostrarEliminarProveedor();
    }//GEN-LAST:event_jXHyperlink6ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        mostrarEliminarProveedor();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        mostrarAsignacionPermisos();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
    objReporte.ejecutarReporte("rptClientes");
}//GEN-LAST:event_jMenuItem9ActionPerformed

private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
    mostrarReportePorSector();
}//GEN-LAST:event_jMenuItem13ActionPerformed

private void jXHyperlink8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink8ActionPerformed
    mostrarProductoMod();
}//GEN-LAST:event_jXHyperlink8ActionPerformed

private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
   mostrarProductoMod();
}//GEN-LAST:event_jMenuItem14ActionPerformed

private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
    mostrarCambioClave();
}//GEN-LAST:event_jMenuItem19ActionPerformed

private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
    objReporte.ejecutarReporte("rptClienteLapsoUltimoPago");
}//GEN-LAST:event_jMenuItem20ActionPerformed

private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
    
    objReporte.ejecutarReporte("rptClienteDeudaTotal");        
}//GEN-LAST:event_jMenuItem21ActionPerformed

private void jXHyperlink9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink9ActionPerformed
    mostrarProductoDel();
}//GEN-LAST:event_jXHyperlink9ActionPerformed

private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
    mostrarKardex();
}//GEN-LAST:event_jMenuItem18ActionPerformed

private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
    objReporte.ejecutarReporte("rptCCAtrasadas");
}//GEN-LAST:event_jMenuItem22ActionPerformed

private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed

    permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmAbrirCaja");
    if(permitido)
    {   
       try{
            ArrayList<clsComboBox> dataFacturero = objFacturero.consultarFactureros();
          
            for(int i=0;i<dataFacturero.size();i=i+1)
            {                          
            }  
            frmAbrirCaja ventana = new frmAbrirCaja(null, true);
            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);
            //dispose();
        }
        catch(Exception ex)
        {       
             JOptionPane.showMessageDialog(null, "No existen factureros activos, ingresar uno para poder abrir caja.", "Atención!", JOptionPane.ERROR_MESSAGE);                 
            
        } 
    }
    else
    {
        JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
    }
}//GEN-LAST:event_btnAbrirActionPerformed

private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
// TODO add your handling code here:
    permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmFacturar");
    if(permitido)
    {   
        //revisar facturero
        String idCajaAbierta = objCaja.obtenerCajaAbierta(main.idUser);
        String factManual = objCaja.comprobarFacturacionManual(idCajaAbierta); 
        if(factManual.equals("S"))
        {            
            int idFacturero = objCaja.obtenerIdFacturero(idCajaAbierta);
            //VERIFICAR SI SE ACABO FACTURERO
            if(objFacturero.consultarEstado(idFacturero).equals("A"))
            {
                frmFacturar ventana = new frmFacturar(null, true);
                ventana.setLocationRelativeTo(null);
                ventana.setVisible(true);
            }
            else if(objFacturero.consultarEstado(idFacturero).equals("T"))
            {    
                JOptionPane.showMessageDialog(this, "Facturero ya terminado, utilice otro", "Atención!", JOptionPane.ERROR_MESSAGE);                 
            }
        }
        else
        {
            frmFacturar ventana = new frmFacturar(null, true);
            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);
        }
    }
    else
    {
        JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
    }   
}//GEN-LAST:event_btnFacturarActionPerformed

private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
// TODO add your handling code here:
     permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmPagoAdd");
    if(permitido)
    {   
        frmPagoAdd ventana = new frmPagoAdd(null, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        //dispose();        
    }
    else
    {
        JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
    }      
}//GEN-LAST:event_btnPagosActionPerformed

private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
// TODO add your handling code here:
    permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmCerrarCaja");
    if(permitido)
    {   
        //frmCerrarCaja ventana = new frmCerrarCaja(null, true);
        //ventana.setLocationRelativeTo(null);
        //ventana.setVisible(true);
        //dispose();
        //if(frmPagoAdd.)
        frmCerrarCaja formulario = new frmCerrarCaja();
        mostrarJInternalCentrado(formulario);   
    }
    else
    {
        JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
    }   
}//GEN-LAST:event_btnCerrarActionPerformed

private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
    mostrarCompras();
}//GEN-LAST:event_jMenuItem23ActionPerformed

private void btnEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgresoActionPerformed
    permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmCerrarCaja");
    if(permitido)
    {   
        frmEgresoDinero formulario = new frmEgresoDinero();
        mostrarJInternalCentrado(formulario);   
    }
    else
    {
        JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
    }   
}//GEN-LAST:event_btnEgresoActionPerformed

private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
    try
    {  
        frmAcerca ventana = new frmAcerca();
        ventana.setLocationRelativeTo(null);
        //ventana.setExtendedState(JFrame.MAXIMIZED_BOTH);
        ventana.setVisible(true);
    }catch (Exception e)
    {    
        System.out.println(e);
    }// TODO add your handling code here:
}//GEN-LAST:event_jMenuItem26ActionPerformed

private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
    permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmNuevoUsuario");
    if(permitido)
    {   
        frmNuevoUsuario formulario = new frmNuevoUsuario();
        mostrarJInternalCentrado(formulario);   
    }
    else
    {
        JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
    }   
}//GEN-LAST:event_jMenuItem15ActionPerformed

private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
    permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmGrupoAdd");
    if(permitido)
    {   
        frmGrupoAdd formulario = new frmGrupoAdd();
        mostrarJInternalCentrado(formulario);   
    }
    else
    {
        JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
    }   
}//GEN-LAST:event_jMenuItem27ActionPerformed

private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
    mostrarProductoDel();
}//GEN-LAST:event_jMenuItem17ActionPerformed

private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
    objReporte.ejecutarReporte("rptClientesCumple");
}//GEN-LAST:event_jMenuItem28ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    mostrarKardex();
}//GEN-LAST:event_jButton1ActionPerformed

private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
     frmRespaldarDB formulario = new frmRespaldarDB();
     mostrarJInternalCentrado(formulario);       
}//GEN-LAST:event_jMenuItem29ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    mostrarCompras();
}//GEN-LAST:event_jButton3ActionPerformed

private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
    frmFacturero formulario = new frmFacturero();
    mostrarJInternalCentrado(formulario);   
}//GEN-LAST:event_jMenuItem30ActionPerformed

private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
    mostrarBuscarFacturas();
}//GEN-LAST:event_jMenuItem31ActionPerformed

private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
    mostrarAuditoria();
}//GEN-LAST:event_jMenuItem32ActionPerformed

private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
    frmEmpleadoAdd formulario = new frmEmpleadoAdd();
    mostrarJInternalCentrado(formulario); 
}//GEN-LAST:event_jMenuItem25ActionPerformed

   void mostrarAuditoria()
   {
       frmAuditoria formulario = new frmAuditoria();
       mostrarJInternalCentrado(formulario);   
   }
   
   void mostrarBuscarFacturas()
   {
       permitido = objPermisos.comprobarPermisoFormulario(main.idUser, "frmFacturaSeek");
       if(permitido)
       {   
           frmFacturaSeek formulario = new frmFacturaSeek();
           mostrarJInternalCentrado(formulario);   
       }
       else
       {
           JOptionPane.showMessageDialog(this, objUtils.msgSinPermisosFormulario, objUtils.msgTitleSinPermisos, JOptionPane.WARNING_MESSAGE);            
       }     
   }
   
    void mostrarModificarProveedores()
    {
        frmProveedorMod formulario = new frmProveedorMod();

        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = formulario.getSize();
        formulario.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
        (desktopSize.height- jInternalFrameSize.height)/2);

        jDesktopPane1.add(formulario);
        formulario.show();
    }     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    @Action
    public void proveedores() {
        frmProveedorMenu formulario = new frmProveedorMenu();    
        mostrarJInternalCentrado(formulario); 
    }

    @Action
    public void reportes() {
    }

    @Action
    public void productos() {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEgreso;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JButton btnPagos;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink1;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink2;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink3;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink4;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink5;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink6;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink7;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink8;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink9;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane2;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane3;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPendiente;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
