/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmAuditoria.java
 *
 * Created on 13-abr-2012, 17:27:45
 */
package index;

import clases.clsAuditoria;
import clases.clsComboBox;
import clases.clsDetalle;
import clases.clsUsuario;
import clases.clsUtils;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import clases.colorFilaTable;

/**
 *
 * @author CKaiser
 */
public class frmAuditoria extends javax.swing.JInternalFrame {
    MiModelo dtmData = new MiModelo();
    clsUsuario objUsuario = new clsUsuario();
    clsAuditoria objAuditoria = new clsAuditoria();
    clsUtils objUtils = new clsUtils();
    /** Creates new form frmAuditoria */
    public frmAuditoria() {
        initComponents();
        
        //CARGAR USUARIOS
        ArrayList<clsComboBox> dataUsuario = objUsuario.consultarUsuarios();        
        for(int i=0;i<dataUsuario.size();i=i+1)
        {
            clsComboBox oItem = new clsComboBox(dataUsuario.get(i).getCodigo(), dataUsuario.get(i).getDescripcion());
            cmbUsuarios.addItem(oItem);            
        }
        
        dtmData.addColumn("Nº");
        dtmData.addColumn("USUARIO");
        dtmData.addColumn("FORMULARIO");
        dtmData.addColumn("FECHA/HORA");
        dtmData.addColumn("DESCRIPCION");
        
        Date fechaActual = new Date();
        txtFecha.setDate(fechaActual);
    }
    
    public class MiModelo extends DefaultTableModel
    {
            @Override
       public boolean isCellEditable (int row, int column)
       {
           // Aquí devolvemos true o false según queramos que una celda
           // identificada por fila,columna (row,column), sea o no editable
          /* if (column == 3)
              return true;*/
           
           return false;
       }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbUsuarios = new javax.swing.JComboBox();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        chkUsuario = new javax.swing.JCheckBox();
        chkFecha = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stinventario.STInventarioApp.class).getContext().getResourceMap(frmAuditoria.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        cmbUsuarios.setEnabled(false);
        cmbUsuarios.setName("cmbUsuarios"); // NOI18N

        txtFecha.setDateFormatString(resourceMap.getString("txtFecha.dateFormatString")); // NOI18N
        txtFecha.setEnabled(false);
        txtFecha.setName("txtFecha"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblData.setModel(dtmData);
        tblData.setName("tblData"); // NOI18N
        jScrollPane1.setViewportView(tblData);

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chkUsuario.setText(resourceMap.getString("chkUsuario.text")); // NOI18N
        chkUsuario.setName("chkUsuario"); // NOI18N
        chkUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkUsuarioItemStateChanged(evt);
            }
        });

        chkFecha.setText(resourceMap.getString("chkFecha.text")); // NOI18N
        chkFecha.setName("chkFecha"); // NOI18N
        chkFecha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkFechaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(chkUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(chkFecha)
                        .addGap(18, 18, 18)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkUsuario)
                        .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkFecha))
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String setUsuario = "";
    String setFecha = "";
    if(this.chkUsuario.isSelected())
    {
        setUsuario ="S";             
    }
    else
    {
        setUsuario ="N";    
    } 
    if(this.chkFecha.isSelected())
    {
        setFecha = "S";            
    }
    else
    {
        setFecha = "N";
    } 
    clsComboBox objUsuariosSelect = new clsComboBox();
    String codigoUsuario = "";
    if(setUsuario.equals("S"))
    {    
        objUsuariosSelect = (clsComboBox)cmbUsuarios.getSelectedItem();
        codigoUsuario = objUsuariosSelect.getCodigo();
    }
    String fecha = "";
    if(setFecha.equals("S"))
    {       
        DateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
        Date date1= txtFecha.getDate();
        fecha = df1.format(date1);
    }
    ArrayList <clsAuditoria> dataAuditoria = objAuditoria.consultarDataAuditoria(
            setUsuario, 
            codigoUsuario, 
            setFecha,
            fecha);
    objUtils.vaciarTabla(dtmData);
    for(int i=0; i<dataAuditoria.size(); i++)
    { 
        Object[] nuevaFila = {
                    i+1 
                    , dataAuditoria.get(i).getUsuario()
                    , dataAuditoria.get(i).getFormulario()
                    , dataAuditoria.get(i).getFecha().substring(0, 16)
                    , dataAuditoria.get(i).getDescripcion()
                   };
        dtmData.addRow(nuevaFila); 
    }
    

}//GEN-LAST:event_jButton1ActionPerformed

private void chkUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkUsuarioItemStateChanged
    if(this.chkUsuario.isSelected())
    {
        cmbUsuarios.setEnabled(true);             
    }
    else
    {
        cmbUsuarios.setEnabled(false);  
    } 
}//GEN-LAST:event_chkUsuarioItemStateChanged

private void chkFechaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkFechaItemStateChanged
    if(this.chkFecha.isSelected())
    {
        txtFecha.setEnabled(true);             
    }
    else
    {
        txtFecha.setEnabled(false);  
    } 
}//GEN-LAST:event_chkFechaItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkFecha;
    private javax.swing.JCheckBox chkUsuario;
    private javax.swing.JComboBox cmbUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    private com.toedter.calendar.JDateChooser txtFecha;
    // End of variables declaration//GEN-END:variables
}
