/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmUsuarioPermisos.java
 *
 * Created on 28/10/2011, 09:42:45 AM
 */
package usuarios;

import clases.clsAuditoria;
import clases.clsComboBox;
import clases.clsPermisos;
import java.util.ArrayList;
import clases.clsUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author CKaiser
 */
public class frmUsuarioPermisos extends javax.swing.JInternalFrame {
    clsUsuario objUsuario = new clsUsuario();
    clsPermisos objPermisos = new clsPermisos();
    clsAuditoria objAuditoria = new clsAuditoria();
    /** Creates new form frmUsuarioPermisos */
    public frmUsuarioPermisos() {
        initComponents();
        
        //CARGAR USUARIOS
        ArrayList<clsComboBox> dataUsuario = objUsuario.consultarUsuarios();        
        for(int i=0;i<dataUsuario.size();i=i+1)
        {
            clsComboBox oItem = new clsComboBox(dataUsuario.get(i).getCodigo(), dataUsuario.get(i).getDescripcion());
            cmbUsuarios.addItem(oItem);            
        }
    }
    
    void vaciarPermisos()
    {
        chkAbrirCaja.setSelected(false);
        chkCerrarCaja.setSelected(false);
        chkFacturar.setSelected(false);
        chkPermisos.setSelected(false);
        chkCreacionUsuario.setSelected(false);
        chkModificarProductos.setSelected(false);
        chkPagos.setSelected(false);
        chkPagosHistorico.setSelected(false);
        chkFactHistorico.setSelected(false);
        chkEliminarProductos.setSelected(false);
        chkKardex.setSelected(false);
        chkRecibir.setSelected(false);
        chkRetirar.setSelected(false);
        chkMantenimientoGrupo.setSelected(false);
        chkAnularFacturas.setSelected(false);
        
    }
    /** This method fis called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbUsuarios = new javax.swing.JComboBox();
        btnGuardar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jideTabbedPane1 = new com.jidesoft.swing.JideTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        chkPermisos = new javax.swing.JCheckBox();
        chkCreacionUsuario = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        chkAbrirCaja = new javax.swing.JCheckBox();
        chkCerrarCaja = new javax.swing.JCheckBox();
        chkFacturar = new javax.swing.JCheckBox();
        chkPagos = new javax.swing.JCheckBox();
        chkAnularFacturas = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        chkPagosHistorico = new javax.swing.JCheckBox();
        chkFactHistorico = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        chkModificarProductos = new javax.swing.JCheckBox();
        chkEliminarProductos = new javax.swing.JCheckBox();
        chkKardex = new javax.swing.JCheckBox();
        chkRecibir = new javax.swing.JCheckBox();
        chkRetirar = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        chkMantenimientoGrupo = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stinventario.STInventarioApp.class).getContext().getResourceMap(frmUsuarioPermisos.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        cmbUsuarios.setName("cmbUsuarios"); // NOI18N
        cmbUsuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUsuariosItemStateChanged(evt);
            }
        });

        btnGuardar.setText(resourceMap.getString("btnGuardar.text")); // NOI18N
        btnGuardar.setEnabled(false);
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnMostrar.setText(resourceMap.getString("btnMostrar.text")); // NOI18N
        btnMostrar.setName("btnMostrar"); // NOI18N
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jideTabbedPane1.setBorder(null);
        jideTabbedPane1.setEnabled(false);
        jideTabbedPane1.setName("jideTabbedPane1"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setEnabled(false);
        jPanel2.setName("jPanel2"); // NOI18N

        chkPermisos.setText(resourceMap.getString("chkPermisos.text")); // NOI18N
        chkPermisos.setEnabled(false);
        chkPermisos.setName("chkPermisos"); // NOI18N

        chkCreacionUsuario.setText(resourceMap.getString("chkCreacionUsuario.text")); // NOI18N
        chkCreacionUsuario.setEnabled(false);
        chkCreacionUsuario.setName("chkCreacionUsuario"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkPermisos)
                    .addComponent(chkCreacionUsuario))
                .addContainerGap(466, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkPermisos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkCreacionUsuario)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jideTabbedPane1.addTab(resourceMap.getString("jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName("jPanel1"); // NOI18N

        chkAbrirCaja.setText(resourceMap.getString("chkAbrirCaja.text")); // NOI18N
        chkAbrirCaja.setName("chkAbrirCaja"); // NOI18N

        chkCerrarCaja.setText(resourceMap.getString("chkCerrarCaja.text")); // NOI18N
        chkCerrarCaja.setName("chkCerrarCaja"); // NOI18N

        chkFacturar.setText(resourceMap.getString("chkFacturar.text")); // NOI18N
        chkFacturar.setName("chkFacturar"); // NOI18N

        chkPagos.setText(resourceMap.getString("chkPagos.text")); // NOI18N
        chkPagos.setName("chkPagos"); // NOI18N
        chkPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPagosActionPerformed(evt);
            }
        });

        chkAnularFacturas.setText(resourceMap.getString("chkAnularFacturas.text")); // NOI18N
        chkAnularFacturas.setName("chkAnularFacturas"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkAbrirCaja)
                        .addGap(79, 79, 79)
                        .addComponent(chkAnularFacturas))
                    .addComponent(chkCerrarCaja)
                    .addComponent(chkFacturar)
                    .addComponent(chkPagos))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAbrirCaja)
                    .addComponent(chkAnularFacturas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkCerrarCaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkFacturar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkPagos)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jideTabbedPane1.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        chkPagosHistorico.setText(resourceMap.getString("chkPagosHistorico.text")); // NOI18N
        chkPagosHistorico.setName("chkPagosHistorico"); // NOI18N

        chkFactHistorico.setText(resourceMap.getString("chkFactHistorico.text")); // NOI18N
        chkFactHistorico.setName("chkFactHistorico"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkFactHistorico)
                    .addComponent(chkPagosHistorico))
                .addContainerGap(421, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(chkFactHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkPagosHistorico)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jideTabbedPane1.addTab(resourceMap.getString("jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N

        chkModificarProductos.setText(resourceMap.getString("chkModificarProductos.text")); // NOI18N
        chkModificarProductos.setName("chkModificarProductos"); // NOI18N

        chkEliminarProductos.setText(resourceMap.getString("chkEliminarProductos.text")); // NOI18N
        chkEliminarProductos.setName("chkEliminarProductos"); // NOI18N

        chkKardex.setText(resourceMap.getString("chkKardex.text")); // NOI18N
        chkKardex.setName("chkKardex"); // NOI18N
        chkKardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKardexActionPerformed(evt);
            }
        });

        chkRecibir.setText(resourceMap.getString("chkRecibir.text")); // NOI18N
        chkRecibir.setName("chkRecibir"); // NOI18N

        chkRetirar.setText(resourceMap.getString("chkRetirar.text")); // NOI18N
        chkRetirar.setName("chkRetirar"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkRetirar)
                    .addComponent(chkRecibir)
                    .addComponent(chkKardex)
                    .addComponent(chkEliminarProductos)
                    .addComponent(chkModificarProductos))
                .addContainerGap(426, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(chkModificarProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkEliminarProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkKardex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkRecibir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkRetirar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jideTabbedPane1.addTab(resourceMap.getString("jPanel4.TabConstraints.tabTitle"), jPanel4); // NOI18N

        jPanel5.setName("jPanel5"); // NOI18N

        chkMantenimientoGrupo.setText(resourceMap.getString("chkMantenimientoGrupo.text")); // NOI18N
        chkMantenimientoGrupo.setName("chkMantenimientoGrupo"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(chkMantenimientoGrupo)
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(chkMantenimientoGrupo)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jideTabbedPane1.addTab(resourceMap.getString("jPanel5.TabConstraints.tabTitle"), jPanel5); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jideTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMostrar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnGuardar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnMostrar))
                .addGap(18, 18, 18)
                .addComponent(jideTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String idModulo="";
        String idFormulario="";
        clsComboBox objUsuarioSelect = (clsComboBox)cmbUsuarios.getSelectedItem();
        //ELIMINAR PERMISOS ACTUALES
        objPermisos.eliminarPermisos(objUsuarioSelect.getCodigo());
         //GUARDAR LOS NUEVOS
        if(this.chkAbrirCaja.isSelected())
        {
            idModulo = "1";
            idFormulario = "2";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkCerrarCaja.isSelected())
        {
            idModulo = "1";
            idFormulario = "3";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkFacturar.isSelected())
        {
            idModulo = "1";
            idFormulario = "4";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkPermisos.isSelected())
        {
            idModulo = "3";
            idFormulario = "5";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkCreacionUsuario.isSelected())
        {
            idModulo = "3";
            idFormulario = "14";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkModificarProductos.isSelected())
        {
            idModulo = "3";
            idFormulario = "6";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkPagos.isSelected())
        {
            idModulo = "1";
            idFormulario = "7";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkPagosHistorico.isSelected())
        {
            idModulo = "1";
            idFormulario = "8";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkFactHistorico.isSelected())
        {
            idModulo = "1";
            idFormulario = "9";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkEliminarProductos.isSelected())
        {
            idModulo = "1";
            idFormulario = "10";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkKardex.isSelected())
        {
            idModulo = "2";
            idFormulario = "11";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkRecibir.isSelected())
        {
            idModulo = "2";
            idFormulario = "12";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkRetirar.isSelected())
        {
            idModulo = "2";
            idFormulario = "13";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkMantenimientoGrupo.isSelected())
        {
            idModulo = "2";
            idFormulario = "15";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        if(this.chkAnularFacturas.isSelected())
        {
            idModulo = "1";
            idFormulario = "16";
            objPermisos.insertarRegistro(objUsuarioSelect.getCodigo(), idModulo, idFormulario);
        }
        
        
        objAuditoria.insertarAuditoria("frmUsuarioPermisos", "CAMBIO DE PERMISOS AL USUARIO:" + objUsuarioSelect.getDescripcion(), "4");
        JOptionPane.showMessageDialog(this, "Datos almacenados con éxito", "Atención!", JOptionPane.INFORMATION_MESSAGE);
        vaciarPermisos(); 
        reinicio();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        //BUSCAR PERMISOS
        vaciarPermisos();
        
        jideTabbedPane1.setEnabled(true);
        jPanel2.setEnabled(true);
        chkPermisos.setEnabled(true);
        chkCreacionUsuario.setEnabled(true);
        String nombreFormulario="";
        clsComboBox objUsuarioSelect = (clsComboBox)cmbUsuarios.getSelectedItem();
        ArrayList<clsPermisos> dataPermisos = objPermisos.consultarPermisosUsuario(objUsuarioSelect.getCodigo());        
        for(int i=0;i<dataPermisos.size();i=i+1)
        {
            nombreFormulario = dataPermisos.get(i).getFormDescripcion();
            if(nombreFormulario.equals("frmAbrirCaja"))
            {
                chkAbrirCaja.setSelected(true);
            }
            if(nombreFormulario.equals("frmCerrarCaja"))
            {
                chkCerrarCaja.setSelected(true);
            }
            if(nombreFormulario.equals("frmFacturar"))
            {
                chkFacturar.setSelected(true);
            }   
            if(nombreFormulario.equals("frmUsuarioPermisos"))
            {
                chkPermisos.setSelected(true);
            }  
            if(nombreFormulario.equals("frmNuevoUsuario"))
            {
                chkCreacionUsuario.setSelected(true);
            } 
            if(nombreFormulario.equals("frmProductosMod"))
            {
                chkModificarProductos.setSelected(true);
            }  
            if(nombreFormulario.equals("frmPagoAdd"))
            {
                chkPagos.setSelected(true);
            } 
            if(nombreFormulario.equals("frmPagoHistoricoAdd"))
            {
                chkPagosHistorico.setSelected(true);
            } 
            if(nombreFormulario.equals("frmFactHisto"))
            {
                chkFactHistorico.setSelected(true);
            } 
            if(nombreFormulario.equals("frmProductosDel"))
            {
                chkEliminarProductos.setSelected(true);
            } 
            if(nombreFormulario.equals("frmKardex"))
            {
                chkKardex.setSelected(true);
            } 
            if(nombreFormulario.equals("frmKardexIngreso"))
            {
                chkRecibir.setSelected(true);
            } 
            if(nombreFormulario.equals("frmGrupoAdd"))
            {
                chkMantenimientoGrupo.setSelected(true);
            } 
            if(nombreFormulario.equals("frmFacturaSeek"))
            {
                chkAnularFacturas.setSelected(true);
            }             
        }
        this.btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnMostrarActionPerformed

private void chkPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPagosActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_chkPagosActionPerformed

private void chkKardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKardexActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_chkKardexActionPerformed

private void cmbUsuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUsuariosItemStateChanged
    reinicio();
}//GEN-LAST:event_cmbUsuariosItemStateChanged

public void reinicio()
{
    jideTabbedPane1.setEnabled(false);
    jideTabbedPane1.setSelectedComponent(jPanel2);
    jPanel2.setEnabled(false);
    chkPermisos.setEnabled(false);
    chkCreacionUsuario.setEnabled(false);
    this.btnGuardar.setEnabled(false);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JCheckBox chkAbrirCaja;
    private javax.swing.JCheckBox chkAnularFacturas;
    private javax.swing.JCheckBox chkCerrarCaja;
    private javax.swing.JCheckBox chkCreacionUsuario;
    private javax.swing.JCheckBox chkEliminarProductos;
    private javax.swing.JCheckBox chkFactHistorico;
    private javax.swing.JCheckBox chkFacturar;
    private javax.swing.JCheckBox chkKardex;
    private javax.swing.JCheckBox chkMantenimientoGrupo;
    private javax.swing.JCheckBox chkModificarProductos;
    private javax.swing.JCheckBox chkPagos;
    private javax.swing.JCheckBox chkPagosHistorico;
    private javax.swing.JCheckBox chkPermisos;
    private javax.swing.JCheckBox chkRecibir;
    private javax.swing.JCheckBox chkRetirar;
    private javax.swing.JComboBox cmbUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private com.jidesoft.swing.JideTabbedPane jideTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
